#Spam News Detection using NLP & Machine Learning
# AI/ML Internship Project – PlaceMantra (AICTE & MSME)

Objective:
To classify news articles as Fake or Real using Natural Language Processing
and Machine Learning techniques.

Dataset:
- True.csv → Real news
- Fake.csv → Fake news

Workflow:
1. Data Loading & Labeling
2. Data Preprocessing (Cleaning + Lemmatization)
3. Feature Extraction (TF-IDF)
4. Model Training (Naive Bayes)
5. Evaluation
6. Prediction

In [ ]:
# Import required libraries
import numpy as np
import pandas as pd
import re
import nltk

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
#Load Dataset
true_news = pd.read_csv("true.csv")
fake_news = pd.read_csv("Fake.csv")

In [ ]:
true_news

                                                text
0  The government has introduced new policies to ...
1  Scientists have developed a new method to dete...
2  The stock market showed steady growth this wee...
3  Renewable energy projects have expanded signif...
4  A new space mission successfully launched sate...
5  Healthcare services in rural areas have improv...

In [ ]:
fake_news

                                                text
0    Aliens spotted over the White House last night.
1  Cure for COVID-19 found in drinking bleach, ex...
2  Scientists confirm Earth is flat after new exp...
3  Time travel machine discovered in ancient Egyp...
4  Drinking soda daily can extend life by 50 year...
5  Secret city found under the Bermuda Triangle w...

In [ ]:
# Add labels
true_news['label'] = 0  # Real News
fake_news['label'] = 1  # Fake News

In [ ]:
true_news

                                                text  label
0  The government has introduced new policies to ...      0
1  Scientists have developed a new method to dete...      0
2  The stock market showed steady growth this wee...      0
3  Renewable energy projects have expanded signif...      0
4  A new space mission successfully launched sate...      0
5  Healthcare services in rural areas have improv...      0

In [ ]:
fake_news

                                                text  label
0    Aliens spotted over the White House last night.      1
1  Cure for COVID-19 found in drinking bleach, ex...      1
2  Scientists confirm Earth is flat after new exp...      1
3  Time travel machine discovered in ancient Egyp...      1
4  Drinking soda daily can extend life by 50 year...      1
5  Secret city found under the Bermuda Triangle w...      1

In [ ]:
dataset1 = true_news[['text', 'label']]
dataset2 = fake_news[['text', 'label']]

In [ ]:
dataset1

                                                text  label
0  The government has introduced new policies to ...      0
1  Scientists have developed a new method to dete...      0
2  The stock market showed steady growth this wee...      0
3  Renewable energy projects have expanded signif...      0
4  A new space mission successfully launched sate...      0
5  Healthcare services in rural areas have improv...      0

In [ ]:
dataset2

                                                text  label
0    Aliens spotted over the White House last night.      1
1  Cure for COVID-19 found in drinking bleach, ex...      1
2  Scientists confirm Earth is flat after new exp...      1
3  Time travel machine discovered in ancient Egyp...      1
4  Drinking soda daily can extend life by 50 year...      1
5  Secret city found under the Bermuda Triangle w...      1

In [ ]:
dataset = pd.concat([dataset1, dataset2])
dataset

                                                text  label
0  The government has introduced new policies to ...      0
1  Scientists have developed a new method to dete...      0
2  The stock market showed steady growth this wee...      0
3  Renewable energy projects have expanded signif...      0
4  A new space mission successfully launched sate...      0
5  Healthcare services in rural areas have improv...      0
0    Aliens spotted over the White House last night.      1
1  Cure for COVID-19 found in drinking bleach, ex...      1
2  Scientists confirm Earth is flat after new exp...      1
3  Time travel machine discovered in ancient Egyp...      1
4  Drinking soda daily can extend life by 50 year...      1
5  Secret city found under the Bermuda Triangle w...      1

In [ ]:
dataset['label'].value_counts()

label
0    6
1    6
Name: count, dtype: int64

In [ ]:
print(dataset.isnull().sum())

text     0
label    0
dtype: int64

In [ ]:
dataset = dataset.sample(frac=1, random_state=42)
dataset

                                                text  label
5  Secret city found under the Bermuda Triangle w...      1
4  Drinking soda daily can extend life by 50 year...      1
5  Healthcare services in rural areas have improv...      0
3  Renewable energy projects have expanded signif...      0
2  The stock market showed steady growth this wee...      0
1  Cure for COVID-19 found in drinking bleach, ex...      1
0    Aliens spotted over the White House last night.      1
3  Time travel machine discovered in ancient Egyp...      1
1  Scientists have developed a new method to dete...      0
0  The government has introduced new policies to ...      0
2  Scientists confirm Earth is flat after new exp...      1
4  A new space mission successfully launched sate...      0

In [ ]:
# Check class distribution
dataset['label'].value_counts()

# Check missing values
dataset.isnull().sum()

text     0
label    0
dtype: int64

##Data Overview
- 0 → Real News
- 1 → Fake News

# NLP

In [ ]:
# Download required resources
nltk.download('wordnet')
nltk.download('stopwords')

lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def clean_news(text):
    text = text.lower()
    text = re.sub('[^a-zA-Z]', ' ', text)
    words = text.split()

    cleaned = [
        lemmatizer.lemmatize(word)
        for word in words if word not in stop_words
    ]

    return " ".join(cleaned)

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [ ]:
# Apply cleaning
dataset['text'] = dataset['text'].apply(lambda x: clean_news(x))
dataset['text']

5    secret city found bermuda triangle advanced ci...
4    drinking soda daily extend life year new study...
5    healthcare service rural area improved due inc...
3    renewable energy project expanded significantl...
2    stock market showed steady growth week increas...
1          cure covid found drinking bleach expert say
0                 alien spotted white house last night
3    time travel machine discovered ancient egyptia...
1    scientist developed new method detect early st...
0    government introduced new policy improve quali...
2          scientist confirm earth flat new expedition
4    new space mission successfully launched satell...
Name: text, dtype: object

In [ ]:

vectorizer = TfidfVectorizer(max_features=50000, lowercase=False, ngram_range=(1,2))
X = dataset.iloc[:, 0]
y = dataset.iloc[:, 1]

In [ ]:
X

5    secret city found bermuda triangle advanced ci...
4    drinking soda daily extend life year new study...
5    healthcare service rural area improved due inc...
3    renewable energy project expanded significantl...
2    stock market showed steady growth week increas...
1          cure covid found drinking bleach expert say
0                 alien spotted white house last night
3    time travel machine discovered ancient egyptia...
1    scientist developed new method detect early st...
0    government introduced new policy improve quali...
2          scientist confirm earth flat new expedition
4    new space mission successfully launched satell...
Name: text, dtype: object

In [ ]:
y

5    1
4    1
5    0
3    0
2    0
1    1
0    1
3    1
1    0
0    0
2    1
4    0
Name: label, dtype: int64

In [ ]:
train_data, test_data, train_label, test_label = train_test_split(X, y, test_size=0.2, random_state=42)
train_data

1    scientist developed new method detect early st...
1          cure covid found drinking bleach expert say
5    healthcare service rural area improved due inc...
4    drinking soda daily extend life year new study...
4    new space mission successfully launched satell...
2    stock market showed steady growth week increas...
3    time travel machine discovered ancient egyptia...
3    renewable energy project expanded significantl...
0                 alien spotted white house last night
Name: text, dtype: object

In [ ]:
# Transform text data
vec_train_data = vectorizer.fit_transform(train_data)
vec_train_data

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 145 stored elements and shape (9, 141)>

In [ ]:
vec_train_data = vec_train_data.toarray()
vec_test_data = vectorizer.transform(test_data)
vec_test_data = vec_test_data.toarray()
vec_train_data.shape,vec_test_data.shape

((9, 141), (3, 141))

In [ ]:
vec_train_data

array([[0.23224873, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.30151134, 0.30151134, ..., 0.30151134, 0.        ,
        0.        ]])

In [ ]:
training_data = pd.DataFrame(vec_train_data,columns = vectorizer.get_feature_names_out())
testing_data = pd.DataFrame(vec_test_data,columns = vectorizer.get_feature_names_out())
training_data

,accuracy,alien,alien spotted,ancient,ancient egyptian,area,area improved,bleach,bleach expert,cancer,...,time travel,tomb,travel,travel machine,week,week increased,white,white house,year,year new
0,0.232249,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.232249,...,0.00000,0.00000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.280459,0.280459,0.000000,...,0.00000,0.00000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.000000,0.000000,0.000000,0.00000,0.00000,0.231166,0.231166,0.000000,0.000000,0.000000,...,0.00000,0.00000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.00000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.248049,0.248049
4,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.00000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.00000,0.00000,0.00000,0.244606,0.244606,0.000000,0.000000,0.000000,0.000000
6,0.000000,0.000000,0.000000,0.27735,0.27735,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.27735,0.27735,0.27735,0.27735,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.00000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,0.000000,0.301511,0.301511,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.00000,0.00000,0.00000,0.000000,0.000000,0.301511,0.301511,0.000000,0.000000

# Model

In [ ]:
# Train Naive Bayes model
clf = MultinomialNB()
clf.fit(training_data, train_label)

MultinomialNB()

In [ ]:
# Predictions
y_pred = clf.predict(testing_data)
test_label

2    1
0    0
5    1
Name: label, dtype: int64

In [ ]:
y_pred

array([0, 0, 1])

In [ ]:
#Accuracy
accuracy_score(test_label,y_pred)

0.6666666666666666

In [ ]:
y_pred_train = clf.predict(training_data)
accuracy_score(train_label,y_pred_train)

1.0

In [ ]:
# Detailed report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.50      1.00      0.67         1
           1       1.00      0.50      0.67         2

    accuracy                           0.67         3
   macro avg       0.75      0.75      0.67         3
weighted avg       0.83      0.67      0.67         3

In [ ]:
text='Aliens spotted over the White House last night.'
news=clean_news(text)
news

'alien spotted white house last night'

In [ ]:
pred = clf.predict(vectorizer.transform([news]).toarray())
pred

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(

array([1])

In [ ]:
if pred[0] == 0:
    print("News is Correct")
else:
    print("News is Fake")

News is Fake

In [ ]:
text='The government has introduced new policies to improve the quality of education across public schools.'
news=clean_news(text)
news

'government introduced new policy improve quality education across public school'

In [ ]:
pred = clf.predict(vectorizer.transform([news]).toarray())
pred

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(

array([0])

In [ ]:
if pred[0] == 0:
    print("News is Correct")
else:
    print("News is Fake")

News is Correct

Conclusion:
- Successfully built a Fake News Detection model
- Achieved good accuracy using Naive Bayes
- NLP techniques improved text understanding

Future Improvements:
- Use Deep Learning (LSTM, BERT)
- Deploy as web app (Streamlit)
- Improve dataset quality